# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # vagrant box add precise64 http://files.vagrantup.com/precise64.box
  config.vm.box = "precise64"
  config.vm.network :hostonly, "33.33.33.11"
  config.vm.forward_port 80, 9080
  
end
