---
# Configuration file defining ruby libraries to install
# using gem install (avoiding the distribution package manager)
#
# Gems are installed for Ruby1.9
gems:
  - addressable
  - cake
  - cheat
  - fastercsv
  - hpricot
  - htmlentities
  - json
  - kwalify
  - libxml-ruby
  - uuidtools
  - xml-simple
  # science
  - bio
  - bio-bwa
  - bio-blastxmlparser
  - biomart
  - ruby-ensembl-api
  # databases
  - couchdb-ruby
  - data_objects
  - datamapper
  - dm-adjust
  - dm-aggregates
  - dm-ar-finders
  - dm-cli
  - dm-constraints
  - dm-core
  - dm-is-list
  - dm-is-nested_set
  - dm-is-remixable
  - dm-is-searchable
  - dm-is-state_machine
  - dm-is-tree
  - dm-is-versioned
  - dm-migrations
  - dm-observer
  - dm-rest-adapter
  - dm-serializer
  - dm-tags
  - dm-timestamps
  - dm-types
  - dm-validations
  - do_sqlite3
  # Require up to date ruby. Fail on Centos default
  - vagrant
  - mysql
  - do_mysql
  - sqlite3-ruby
  # Problems building on 1.9.1
  #- dm-ferret-adapter
  #- dm-sweatshop
